# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
